### ISSUE TITLE
How to use protoc-gen-openapiv2 on my own proto file

### ISSUE THREAD

**Issue by rantianhua** [grpc-ecosystem/grpc-gateway#2027]
## 📚 Documentation

I want to use protoc-gen-openapiv2 options on my own proto file. 

My installation:
```
// +build tools

package tools

import (
	_ "github.com/envoyproxy/protoc-gen-validate"
	_ "github.com/go-swagger/go-swagger/cmd/swagger"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2"
	_ "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
	_ "google.golang.org/protobuf/cmd/protoc-gen-go"
)
```

My buf.gen.yaml:

```
version: v1beta1

# The plugins to run.
plugins:
  # Backend
  - name: go
    out: &backend_output ../../proto-gen
    opt: paths=source_relative
  - name: validate
    out: *backend_output
    opt: lang=go,paths=source_relative
  - name: go-grpc
    out: *backend_output
    opt: paths=source_relative,require_unimplemented_servers=false
  - name: grpc-gateway
    out: *backend_output
    opt: paths=source_relative
  - name: openapiv2
    out: *backend_output
    opt: fqn_for_openapi_name=true,include_package_in_tags=true
```

My proto file:

```
import "protoc-gen-openapiv2/options/annotations.proto";

service XXXService {
  rpc Verify(XXXRequest) returns (XXXResponse) {
    option (google.api.http) = {
      post: "/v1/xxx/verification"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "Summary: XXX"
      description: "xxx."
      responses: { key: "200" }
    };
  }
}
```

An error occurred when running `buf generate`:
```
protoc-gen-openapiv2/options/annotations.proto: does not exist
```

What's wrong with my installation or import that causes the compiler cannot find options?
