### ISSUE TITLE
Generated OpenAPI document fails validation on parameters in path

### ISSUE THREAD

**Issue by someone1** [grpc-ecosystem/grpc-gateway#2084]
## 🐛 Bug Report

Take the example [a little bit of everything](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.swagger.json) swagger file and pop it into swagger editor/UI - it will fail validation checks

This feels like the issues raised in #720 and #1015 though I didn't want to bump an older issue or hijack another issue that seemed more specific.

Sometimes the path annotations generate fine in the OpenAPI document and other times not. For example, the following annotrations seem to work:

```proto
option (google.api.http) = {
      get: "/v1alpha/{user=users/*}/noun:verb"
    };

option (google.api.http) = {
      post: "/v1alpha/{user=users/*}/noun2:verb"
      body: "*"
    };
```

Generates:

```yaml
"/v1alpha/{user}/noun:verb": {
      "get": {
        "parameters": [
          {
            "name": "user",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
    }
}
"/v1alpha/{user}/advice:generate": {
      "post": {
        "parameters": [
          {
            "name": "user",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1alphaVerbRequest"
            }
          }
        ],
    }
}
```

However, the following does not:

```proto
    option (google.api.http) = {
      get: "/v1alpha/{parent=users/*}/accounts"
    };
    option (google.api.http) = {
      get: "/v1alpha/{name=users/*/accounts/*}"
    };
```

Generates:

```yaml
 "/v1alpha/{parent=users/*}/accounts": {
      "get": {
        "parameters": [
          {
            "name": "parent",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
    }
}
 "/v1alpha/{name=users/*/accounts/*}": {
      "get": {
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
    }
}
```

Interestingly, in the example above that doesn't' work, renaming `parent=` to `user=` generates properly!

```proto
    option (google.api.http) = {
      get: "/v1alpha/{user=users/*}/accounts"
    };
```
```yaml
  "/v1alpha/{user}/accounts": {
      "get": {
        "parameters": [
          {
            "name": "user",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
   }
}
```

Does the generator expect specific values in which it will trigger the correct generation in the OpenAPI spec for the path annotations? Switching from `parent` to `user` to fix one such case of issues sounds buggy to me. I'm not certain how the second example `/v1alpha/{name=users/*/accounts/*}` should map to query params in the OpenAPI spec, but the URL should probably look like `/v1alpha/users/*/accounts/*` - I think the gateway itself processes all this okay, its just the generated OpenAPI spec that's falling short.

Generated w/ v2.3.0
