### ISSUE TITLE
gRPC Gateway behind Ingress : Failed to extract ServerMetadata from context

### ISSUE THREAD

**Issue by bleleve** [grpc-ecosystem/grpc-gateway#2445]
Hello everyone, I hope you are well.

## 🐛 Bug Report

I am facing a "bug", I don't think it is directly related to grpc-gateway, but any help would be greatly appreciated, I have been stuck on this for a few days. 

Our gRPC API developed in Go has been running since 2017 at DigitalOcean on an unmanaged Kubernetes cluster with a load-balancer, an NginX ingress controller but with the proxy protocol disabled (it was not supported by DO). We are currently migrating to a managed k8s cluster at Scaleway with an LB, an NginX ingress controller but with the proxy protocol v2 enabled.

The gRPC service call works, whether it is in direct node access or through the ingress. The REST call works in direct node access (NodePort) but returns an error message through the ingress: "Failed to extract ServerMetadata from context" (https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/handler.go#L137).

## Your Environment

Kubernetes 1.22.3
NginX Ingress Controller 1.0.4

Go 1.17+
protoc 3.18.0
google.golang.org/grpc v1.40.0
google.golang.org/protobuf v1.27.1
github.com/grpc-ecosystem/go-grpc-middleware v1.3.0
github.com/grpc-ecosystem/grpc-gateway/v2 v2.6.0

**NginX conf**
```
[...]
server {
	server_name rest.api.example.com ;
	
	listen 80 proxy_protocol ;
	listen [::]:80 proxy_protocol ;
	listen 443 proxy_protocol ssl http2 ;
	listen [::]:443 proxy_protocol ssl http2 ;
	
	set $proxy_upstream_name "-";
	
	ssl_certificate_by_lua_block {
		certificate.call()
	}
	
	location ~* "^/v1.1" {
		rewrite_by_lua_block {
			lua_ingress.rewrite({
				force_ssl_redirect = false,
				ssl_redirect = true,
				force_no_ssl_redirect = false,
				preserve_trailing_slash = false,
				use_port_in_redirects = false,
				global_throttle = { namespace = "", limit = 0, window_size = 0, key = { }, ignored_cidrs = { } },
			})
			balancer.rewrite()
			plugins.run()
		}
		
		header_filter_by_lua_block {
			lua_ingress.header()
			plugins.run()
		}
		
		body_filter_by_lua_block {
			plugins.run()
		}
		
		log_by_lua_block {
			balancer.log()
			
			monitor.call()
			
			plugins.run()
		}
		
		port_in_redirect off;
		
		set $balancer_ewma_score -1;
		set $proxy_upstream_name "h6s-beez-test-apiengine-service-8443";
		set $proxy_host          $proxy_upstream_name;
		set $pass_access_scheme  $scheme;
		
		set $pass_server_port    $proxy_protocol_server_port;
		
		set $best_http_host      $http_host;
		set $pass_port           $pass_server_port;
		
		set $proxy_alternative_upstream_name "";
		
		client_max_body_size                    1m;
		
		proxy_set_header Host                   $best_http_host;
		
		# Pass the extracted client certificate to the backend
		
		# Allow websocket connections
		proxy_set_header                        Upgrade           $http_upgrade;
		
		proxy_set_header                        Connection        $connection_upgrade;
		
		proxy_set_header X-Request-ID           $req_id;
		proxy_set_header X-Real-IP              $remote_addr;
		
		proxy_set_header X-Forwarded-For        $remote_addr;
		
		proxy_set_header X-Forwarded-Host       $best_http_host;
		proxy_set_header X-Forwarded-Port       $pass_port;
		proxy_set_header X-Forwarded-Proto      $pass_access_scheme;
		proxy_set_header X-Forwarded-Scheme     $pass_access_scheme;
		
		proxy_set_header X-Scheme               $pass_access_scheme;
		
		# Pass the original X-Forwarded-For
		proxy_set_header X-Original-Forwarded-For $http_x_forwarded_for;
		
		# mitigate HTTPoxy Vulnerability
		# https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
		proxy_set_header Proxy                  "";
		
		# Custom headers to proxied server
		
		proxy_connect_timeout                   5s;
		proxy_send_timeout                      60s;
		proxy_read_timeout                      60s;
		
		proxy_buffering                         off;
		proxy_buffer_size                       4k;
		proxy_buffers                           4 4k;
		
		proxy_max_temp_file_size                1024m;
		
		proxy_request_buffering                 on;
		proxy_http_version                      1.1;
		
		proxy_cookie_domain                     off;
		proxy_cookie_path                       off;
		
		# In case of errors try the next upstream server before returning an error
		proxy_next_upstream                     error timeout;
		proxy_next_upstream_timeout             0;
		proxy_next_upstream_tries               3;
		
		rewrite "(?i)/v1.1" / break;
		proxy_pass https://upstream_balancer;
		
		proxy_redirect                          off;
	}		
}
[...]
```

Best regards.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! I've frankly no idea what's going on here, but I should say that the warning log your are seeing is only that - a warning. Are you seeing any difference in behavior from your server?

**Comment by bleleve** [comment]
Hi ans thanks for your answer. Yes, the request stop and an error is sent to the client (code 5, not found).

I hadn't noticed that it was an Info log that was returned ... I'm annoyed, it's like the guy looking for his glasses that are on his nose.

There is something in the generated NginX conf that is causing this, I will check that on Monday.

Thank you and have a nice week-end.

**Comment by johanbrandhorst** [comment]
Alright, I will close this issue for now but let me know if you found there to be an issue with the gateway and we can reopen it. Have a good weekend!

**Comment by bleleve** [comment]
Hi,

The problem is caused by a change in the way the Ingress NginX "rewrite-target" annotation is handled. A capture group is mandatory.

You served me as a rubber duck, sorry for the inconvenience ;)

**Comment by dgurns** [comment]
I'm glad you posted this because I'm running into the same issue. I will check the request forwarding. Thanks for posting!

**Comment by bleleve** [comment]
Making the API available in a subfolder involves going through a `rewrite-target` annotation (we handle versioning this way but it may be for another reason).

Prior to [NginX Ingress 0.22.0](https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.22.0)
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress-rest
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/ssl-services: api-service
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - rest.api.example.com
    secretName: api-ingress-rest-certs
  rules:
  - host: rest.api.example.com
    http:
      paths:
      - path: /v1.1
        backend:
          serviceName: api-service
          servicePort: 8443
```

Now (NginX Ingress 1.0.4 with k8s 1.22.3 ):
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress-rest
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - rest.api.example.com
      secretName: api-ingress-rest-certs
  rules:
    - host: rest.api.example.com
      http:
        paths:
          - path: /v1.1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 8443
```
