### ISSUE TITLE
HTTP rules without a matching selector

### ISSUE THREAD

**Issue by shettyh** [grpc-ecosystem/grpc-gateway#2550]
## 🐛 Bug Report

Getting the error `HTTP rules without a matching selector ....` when multiple folders present in the root directory 

Dir structure
```
 - proto
       - folder1
           - my_service1.proto
       - folder2
           - my_service2.proto
```

Sample `grpc_api_configuration` file

```
type: google.api.Service
config_version: 3

http:
  rules:
    - selector: test.my_service.v1.TestService.Check
      get: "/v1/healthcheck"
```

then do `buf generate proto` with `grpc_api_configuration` file. Generation will fail with error `Failure: plugin grpc-gateway: HTTP rules without a matching selector:  .....`. 

Seems like it is searching for the selector in each folder and throwing error even if it is not found in one of the folder
