### ISSUE TITLE
protoc --grpc-gateway_out does not generate stubs for c++

### ISSUE THREAD

**Issue by Closius** [grpc-ecosystem/grpc-gateway#2649]
I have a gRPC server in Python, gRPC client in Python and C++ and I have RESTfull service using grpc-gateway. For all of then I use one .proto file (to avoid duplication). 

The issue is in the compilation of .proto for C++. I can not generate  *.pb.gw.cpp file. And actually I don't really need it. But I don't know how to ignore following lines while generating .proto:

`import "protoc-gen-openapiv2/options/annotations.proto"; // https://github.com/grpc-ecosystem/grpc-gateway

// These annotations are used when generating the OpenAPI file.
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    version: "1.0";
  };
  schemes: HTTPS;
};`

Because if I don't generate  *.pb.gw.cpp file then C++ Linker will have a problem with unresolved symbol. I found how to fix it, but I think it is not a good idea https://stackoverflow.com/a/2326554/4432498 

Please help..

**Comment by achew22** [comment]
Unfortunately, I think there may be some kind of miscommunication around the project. So far as I know, the project doesn't ever generate `*.pb.gw.cpp` files, it only generates Go source code.

You might consider going through our [tutorial](https://grpc-ecosystem.github.io/grpc-gateway/docs/tutorials/) and building a small project that exhibits the concern you have and upload it to github. If you do, we will be able to have a much more productive conversation around what is and isn't working. What do you think about that?

**Comment by johanbrandhorst** [comment]
I think there is some confusion here. You will need to generate C++ code for all your protobuf dependencies, including `protoc-gen-openapiv2`. The easiest way to do that would be to use `buf` and the module we host on the Buf schema registry: https://buf.build/grpc-ecosystem/grpc-gateway.

1. Define a `buf.gen.yaml`. In your case, using `C++` and `Python`:
   ```yaml
   version: v1
   plugins:
     - remote: buf.build/protocolbuffers/plugins/cpp
       out: gen/cpp
     - remote: buf.build/grpc/plugins/cpp
       out: gen/cpp
     - remote: buf.build/protocolbuffers/plugins/python
       out: gen/python
     - remote: buf.build/grpc/plugins/python
       out: gen/python
   ```
   This makes use of the BSR [remote plugin execution](https://docs.buf.build/bsr/remote-generation/remote-plugin-execution).

2. Generate:
   ```shell
   $ buf generate buf.build/grpc-ecosystem/grpc-gateway
   ```

You'll end up with files you can use to satisfy your imports:

```shell
$ $ tree gen
gen
├── cpp
│   └── protoc-gen-openapiv2
│       └── options
│           ├── annotations.grpc.pb.cc
│           ├── annotations.grpc.pb.h
│           ├── annotations.pb.cc
│           ├── annotations.pb.h
│           ├── openapiv2.grpc.pb.cc
│           ├── openapiv2.grpc.pb.h
│           ├── openapiv2.pb.cc
│           └── openapiv2.pb.h
└── python
    └── protoc_gen_openapiv2
        └── options
            ├── annotations_pb2_grpc.py
            ├── annotations_pb2.py
            ├── openapiv2_pb2_grpc.py
            └── openapiv2_pb2.py

6 directories, 12 files
```
