### ISSUE TITLE
Proto enums can produce invalid yaml in swagger files

### ISSUE THREAD

**Issue by ianrose14** [grpc-ecosystem/grpc-gateway#2745]
## 🐛 Bug Report

If an input proto file contains an enum where some of the individual enum values have comments, the yaml produced by the `protoc-gen-openapiv2` plugin can be invalid.

## To Reproduce

1. Start with a proto file like the following: 
```proto
syntax = "proto3";
package repro;
option go_package = "repro/foobar";

import "google/api/annotations.proto";

service Repro {
    rpc GetRollup(RollupRequest) returns (RollupResponse) {
        option (google.api.http) = {
	  get: "/rollup"
        };
    }
}

message RollupRequest {
  RollupType type = 1;
}
message RollupResponse {}

enum RollupType {
    UNKNOWN_ROLLUP = 0;

    // Apples are good
    APPLE = 1;
    BANANA = 2;

    // Carrots are mediocre
    CARROT = 3;
}
```
2. Name it `repro.proto` and save it in a directory named `repro` along with the usual [annotations.proto](https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto) and [http.proto](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) files.
3. Run the following command:
```sh
protoc repro/repro.proto --proto_path=repro \
    --openapiv2_out=repro --openapiv2_opt logtostderr=true --openapiv2_opt output_format=yaml
```
4. The resulting file (`repro.swagger.yaml`) is invalid.  You can verify this with [various online yaml parsers](https://yaml-online-parser.appspot.com/) or with a small Go program like this:
```go
package main

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v2"
)

func main() {
	r, err := os.Open("repro/repro.swagger.yaml")
	if err != nil {
		panic(err)
	}

	m := make(map[string]any)
	err = yaml.NewDecoder(r).Decode(m)
	if err != nil {
		panic(err)
	}

	fmt.Printf("ok: +%v\n", m)
}
```

For convenience, here's the bit of the yaml that comes out broken:
```yaml
            parameters:
                - name: type
                  description: |4-
                     - APPLE: Apples are good
                     - CARROT: Carrots are mediocre
                  in: query
                  required: false
```

## Expected behavior

The swagger file produced should be valid yaml.

## Actual Behavior

The swagger file is invalid yaml.

## Your Environment

Darwin MacBook-Pro 21.5.0
macOS v12.5
`protoc --version` --> `libprotoc 3.19.4`
`go version` --> `go version go1.18.3 darwin/arm64`
