### ISSUE TITLE
Support custom tags for openapi operation

### ISSUE THREAD

**Issue by defool** [grpc-ecosystem/grpc-gateway#2751]
## 🚀 Feature

Swagger UI uses tags to group the displayed operations, but now we can't set  custom tag to rpc methods ( or operations in openapi).

I thank we can support it in the file specified by  `grpc_api_configuration` option, for example:
```
type: google.api.Service
config_version: 3

http:
  rules:
    - selector: grpc.gateway.examples.internal.proto.examplepb.UnannotatedEchoService.Echo
      post: "/v2/example/echo/{id}"
      tags:
     - example
```

And the tags will be present in [the tags of operation](https://swagger.io/docs/specification/2-0/grouping-operations-with-tags/).
