### ISSUE TITLE
OpenAPIv2 YAML format does not include extensions

### ISSUE THREAD

**Issue by hasit** [grpc-ecosystem/grpc-gateway#2795]
## 🐛 Bug Report

I have a field `bar` in a message `Foo` for which I would like to generate swagger documentation.

```proto
message Foo {
  google.protobuf.Duration bar = 2 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
    description: "This is bar"
    extensions: {
      key: "x-go-default";
      value {
        string_value: "0.5s"
      }
    }
  }]; // @gotags: default:"0.5s"
}
```

Upon generation, I see the description field being generated correctly, but not the x-go-default field. 

## To Reproduce

I use the following `buf.gen.yaml` openapiv2 plugin options:

```
  - remote: buf.build/grpc-ecosystem/plugins/openapiv2:v2.10.3-1
    out: gen/openapiv2
    opt:
      - json_names_for_fields=false
      - merge_file_name=file
      - allow_merge=true
      - output_format=yaml
      - generate_unbound_methods=true
```

After changing `output_format=yaml` to `output_format=json` , the `x-*` fields started showing up.

## Expected behavior

Expect output to contain `x-go-default` field populated with "0.5s" value.

## Actual Behavior

Actual output contains all fields apart from the extensions provided.

## Your Environment

Remote plugin via buf: buf.build/grpc-ecosystem/plugins/openapiv2:v2.10.3-1
Operating system: Pop!_OS 22.04 LTS x86_64

**Comment by johanbrandhorst** [comment]
Thanks for this detailed issue. If someone is interested in trying to fix this, I would suggest starting by adding a failing test. Look at the tests added in https://github.com/grpc-ecosystem/grpc-gateway/pull/2579 for inspiration.

As a workaround for this issue, there appear to be lots of different tools available for converting JSON to YAML as a post-processing step: https://www.google.com/search?client=firefox-b-d&q=json2yaml.

**Comment by hedhyw** [comment]
Fixed in PR #2797

@hasit Please check on your project.

**Comment by hasit** [comment]
@hedhyw I am not sure how I could verify this change. I am using buf system to run this plugin

```
  - remote: buf.build/grpc-ecosystem/plugins/openapiv2:v2.10.3-1
    out: gen/openapiv2
    opt:
      - json_names_for_fields=false
      - merge_file_name=aperture
      - allow_merge=true
      - output_format=json
      - generate_unbound_methods=true
```

**Comment by johanbrandhorst** [comment]
@hasit it won't be available on the BSR until we've made a release. If you want to test the change locally, you'll have to build a binary locally. Since the PR is on a fork, it's a little complicated to test before we've merged it. You could check out the PR locally and run `go build ./protoc-gen-openapiv2` and then use the following `buf.gen.yaml`:

```yaml
  - name: openapiv2
    path: ./<path to built protoc-gen-openapiv2>
    out: gen/openapiv2
    opt:
      - json_names_for_fields=false
      - merge_file_name=file
      - allow_merge=true
      - output_format=json
      - generate_unbound_methods=true
```

But we should get this merged soon, I'm looking at the PR, and then you can install directly using `go install`.
