### ISSUE TITLE
"disable_default_responses" flag hide service proto messages, but not default error

### ISSUE THREAD

**Issue by gvencadze** [grpc-ecosystem/grpc-gateway#3056]
## 🐛 Bug Report

If I set "disable_default_responses" flag to true, than my proto service messages disappear, but default error still exist in docs. I've tried to update all dependencies, move flag from bottom to top, tried to move configuration from external yaml's to proto file with service, but no result.

## To Reproduce

1. Create proto service with external configuration in yaml's (both grpc_api_configuration and openapi_configuration)
2. Run buf generate on it
3. Open generated docs

## Expected behavior

I expect that default gRPC error will disappear and I'll see my custom error instead of it

## Actual Behavior

I got both errors - default, and my custom error

## Your Environment

| instrument  |  version  | 
|---|---|
| OS  | macOS 12   | 
|  Go | 1.19.3 darwin/arm64  | 
| protoc-gen-grpc-gateway  | v2.14.0  | 
| protoc-gen-openapiv2  | v2.14.0  | 
| buf | v1.9.0 |

## My files:
```
#buf.gen.yaml
version: v1
plugins:
  - name: go
    out: gen/go
    opt:
      - paths=source_relative

  - name: go-grpc
    out: gen/go
    opt:
      - paths=source_relative

  - name: grpc-gateway
    out: gen/go
    opt:
      - paths=source_relative
      - grpc_api_configuration=proto/api/sample/v2/sample_annotations.yaml

  - name: openapiv2
    out: gen/openapiv2
    opt:
      - output_format=yaml
      - grpc_api_configuration=proto/api/sample/v2/sample_annotations.yaml
      - openapi_configuration=proto/api/sample/v2/sample_swagger.yaml
      - allow_merge=true
      - merge_file_name=sample
      - disable_default_responses=true
    strategy: all
```

```
#sample_swagger.yaml
openapiOptions:
  file:
    - file: "api/sample/v2/sample.proto"
      option:
        info:
          title: ...
          contact:
            name: ...
            url: ...
            email: ...
          version: "v2.0"
  service:
    - service: api.sample.v2.SampleService
```

```
#sample_annotations.yaml
type: google.api.Service
config_version: 3

http:
  rules:
    - selector: api.sample.v2.SampleService.DoSmth
      get: /api/v2/sample/do.smth
    - selector: api.sample.v2.SampleService.GetSmth
      get: /api/v2/sample/get.smth
```

```
#sample.proto
syntax = "proto3";

package api.sample.v2;

option go_package = "gitlab.example.com/orgname/sample-service/gen/go/api/sample/v2;samplev2";

import "validator/validator.proto";

service SampleService {
  rpc DoSmth(DoSmthRequest) returns (DoSmthResponse) {}
  rpc GetSmth(GetSmthRequest) returns (GetSmthResponse) {}
}

message DoSmthRequest {
  string filename = 1 [(validator.field) = {string_not_empty: true}];
}

message DoSmthResponse {}

message GetSmthRequest {
  string filename = 1 [(validator.field) = {string_not_empty: true}];
}

message GetSmthResponse {
  string url = 1;
}
```
