### ISSUE TITLE
Question: How to use grpc_api_configuration when using grpc-agteway remote plugin?

### ISSUE THREAD

**Issue by DGuhr** [grpc-ecosystem/grpc-gateway#3217]
## 📚 Documentation

Hi 👋 I want to dockerize the generation of gateway code for my makefile, using the bufbuild/buf docker container and remote plugins. Now I struggle with generating the gateway code and cannot find a good doc on that one, so I added it under "documentation" for now.

My config in `buf.gen.yaml` is: 
```
...
  - plugin: buf.build/grpc-ecosystem/gateway
    out: gen
    opt:
      - paths=source_relative
      - grpc_api_configuration=gw_mapping.yaml
...
```

and I've put everything in a flat folder structure to try it out. 

Then i cd inside that folder and run ```docker run --rm -v `pwd`:`pwd` -w `pwd` bufbuild/buf generate .``` 

Result: It generates the *.pb.go and *_grpc.pb.go in a former step also using remote plugins, so I guess that works generally. 

But: It always fails with `Failure: plugin "buf.build/grpc-ecosystem/gateway:v2.15.2" failed: failed to read gRPC API Configuration description from "gw_mapping.yaml": open gw_mapping.yaml: no such file or directory
` and tbh I have no clue if what I try to achieve here is even possible :) The examples at https://github.com/grpc-ecosystem/grpc-gateway#usage-with-remote-plugins don't use it. So would be great to clarify!
