### ISSUE TITLE
Adding custom mux endpoint to openapi output

### ISSUE THREAD

**Issue by joshgarnett** [grpc-ecosystem/grpc-gateway#4105]
The documentation at https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/binary_file_uploads/ is super helpful.  One thing that isn't clear to me though is how we can define that in the proto file or some other external file so it gets included in the openapi json output.  Is there a recommended way to do this or do I need to manually update the json file after it's generated for the additional apis?  Thanks in advance!

**Comment by kamesh-09** [comment]
You can have a json file similar to openapi output - having paths as key - with upload endpoints. Once openapi output is generated you can patch your custom file into generated output. To automate this via script.
You can define patch file as:

`{
  "paths": {
    "upload_endpoint": {
      "methodType[post]": {
        "requestBody": {.....}
      }
    }
  }
}`

**Comment by johanbrandhorst** [comment]
As Kamesh says, this is a post-processing step at the moment, there's no support for including it in the output generated by protoc-gen-openapiv2. I think Kamesh is talking about using https://jsonpatch.com/ perhaps? But any way you want to post-process the file should work. I've used Go before.

**Comment by joshgarnett** [comment]
For anyone else going down this path, here is an example patch file you can use:

```yaml
{
  "paths": {
    "/v1/file": {
      "post": {
        "summary": "Upload a file",
        "operationId": "Service_UploadFile",
        "consumes": [
          "multipart/form-data"
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1UploadFileResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "file",
            "description": "The file being to be uploaded.",
            "in": "formData",
            "required": true,
            "type": "file"
          }
        ],
        "tags": [
          "Service"
        ]
      }
    }
  },
  "definitions": {
    "v1UploadFileResponse": {
      "type": "object",
      "properties": {
        "file": {
          "$ref": "#/definitions/apiSomeOtherProtobuf"
        }
      }
    }
  }
}
```

For merging the json, I just tossed together a simple python script

```python
#!/usr/bin/env python3

import argparse
import json
import mergedeep


def main():
    parser = argparse.ArgumentParser(description='Merges two json files')
    parser.add_argument('-b', '--base', required=True, help="the base json file")
    parser.add_argument('-p', '--patch', required=True, help="the patch json file")
    parser.add_argument('-o', '--out', required=True, help="the file to write the output to")
    args = parser.parse_args()

    with open(args.base) as f:
        base = json.load(f)

    with open(args.patch) as f:
        patch = json.load(f)

    mergedeep.merge(base, patch)

    with open(args.out, 'w') as f:
        json.dump(base, f, indent=2)


if __name__ == '__main__':
    main()
```
