### ISSUE TITLE
undefined: grpc.NewClient

### ISSUE THREAD

**Issue by groeney** [grpc-ecosystem/grpc-gateway#4350]
## 🐛 Bug Report

v2.20.0 introduces the use of grpc.NewClient(...).  This causes a (typecheck) error upon compiling the generated protobuf files. 

```pkg/api/v1/chat_service.pb.gw.go:3423:20: undefined: grpc.NewClient) (typecheck)```

## To Reproduce

1. Explicitly set the version of this package to v2.20.0 in `buf.gen.yaml`

```
version: v1
plugins:
  ...
  # generate reverse proxy from protocol definitions
  - plugin: buf.build/grpc-ecosystem/gateway:v2.20.0
    out: ../../pkg/api
    opt: paths=source_relative
```

2. Generate protobuf files with buf --version == 1.32.0

```
buf generate
```

3. Inspect the output

// service.pb.gw.go

Was
```
// RegisterChatServiceHandlerFromEndpoint is same as RegisterChatServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterChatServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterChatServiceHandler(ctx, mux, conn)
}
```

Now
```
// RegisterChatServiceHandlerFromEndpoint is same as RegisterChatServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterChatServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterChatServiceHandler(ctx, mux, conn)
}
```

4. Observe compiler error

```
undefined: grpc.NewClient compiler[UndeclaredImportedName](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#UndeclaredImportedName)
```

5. Explicitly set the version of this package to v2.19.1 in `buf.gen.yaml`

```
version: v1
plugins:
  ...
  # generate reverse proxy from protocol definitions
  - plugin: buf.build/grpc-ecosystem/gateway:v2.19.1
    out: ../../pkg/api
    opt: paths=source_relative
```

6. Generate protobuf files with buf --version == 1.32.0

```
buf generate
```

7. Inspect the output (unchanged)

## Expected behavior

I expect there not to be a compiler error.

## Actual Behavior

There is a compiler error.

## Your Environment

This happens on Unix and our Linux CI environment. Other versions that may be useful

```
go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
```
