### ISSUE TITLE
buf: failed to read gRPC API Configuration description: no such file or directory

### ISSUE THREAD

**Issue by ffauzann** [grpc-ecosystem/grpc-gateway#4394]
I tried to use `buf@v1.32.2` with `buf.build/grpc-ecosystem/gateway:v2.20.0` remote plugin. But it gives me this error : 
```sh
$ buf generate
Failure: plugin "buf.build/grpc-ecosystem/gateway:v2.20.0" failed: failed to read gRPC API Configuration description from "user.yaml": open user.yaml: no such file or directory
```
Even though when I tried directly using this command, the issue is gone :
```sh
$ protoc -I . \                                                                                                                                                                    ─╯
         --grpc-gateway_out . \
         --grpc-gateway_opt paths=source_relative \
         --grpc-gateway_opt grpc_api_configuration=user.yaml \
         user.proto
``` 

And this is my `buf.gen.yaml` : 

```yaml
version: v2
plugins:
  - remote: buf.build/protocolbuffers/go:v1.33.0
    out: .
    opt: paths=source_relative
  - remote: buf.build/grpc/go:v1.3.0
    out: .
    opt:
      - require_unimplemented_servers=false
      - paths=source_relative  
  - remote: buf.build/grpc-ecosystem/gateway:v2.20.0
    out: .
    opt:
      - paths=source_relative
      - grpc_api_configuration=user.yaml
  - remote: buf.build/grpc-ecosystem/openapiv2:v2.16.2
    out: .
```

Am I missing something?
