### ISSUE TITLE
ERROR: Failed to extract ServerMetadata from context

### ISSUE THREAD

**Issue by andreslunchbox** [grpc-ecosystem/grpc-gateway#4605]
After upgrading from **github.com/grpc-ecosystem/grpc-gateway/v2 v2.18.1** to **github.com/grpc-ecosystem/grpc-gateway/v2 v2.21.0**, I am encountering the following error multiple times even when I'm not making API calls to the gateway:

```
2024/08/07 17:23:39 ERROR: Failed to extract ServerMetadata from context
```

**gRPC-Gateway version:** v2.21.0
**Environment:** AWS ALB Ingress Controller + Gateway running on Kubernetes with EKS

**Additional Context:**
I've observed this error consistently after upgrading the grpc-gateway version. It appears when the gateway is behind AWS ALB Ingress Controller as it does not show up in local development when using an NGINX ingress.

**Comment by johanbrandhorst** [comment]
This error message usually appears when a wrapped `http.ResponseWriter` which doesn't implement the `http.ResponseController` unwrap (see https://www.alexedwards.net/blog/how-to-use-the-http-responsecontroller-type). I can't tell you why these are only appearing in your AWS deployment, presumably they are from random incoming requests? There's no reason to think they should be happening without any sort of incoming requests. If you think there's a bug here, could you provide a minimal working example?

**Comment by andreslunchbox** [comment]
I took a look at the link you provided, but I don't think we have changed anything around that. In fact or gateway setup has been pretty consistent for over a year now, we always follow the same pattern when exposing new microservices which pretty much is:

```go
import "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"

func main() {
      grpcPort := config.Get("GRPC_PORT")
      httpPort := config.Get("HTTP_PORT")
      
      grpcServerEndpoint := fmt.Sprintf("%s:%s", "", grpcPort)
      httpServerEndpoint := fmt.Sprintf("%s:%s", "", httpPort)
      
      lis, err := net.Listen("tcp", grpcServerEndpoint)
      if err != nil {
          logger.Fatal("Failed to listen", "error", err)
      }

    authServer := auth.NewServer()

    authpb.RegisterAuthenticationServiceServer(grpcServer, authServer)
    authpb.RegisterAuthenticationServiceHandlerFromEndpoint(ctx, mux, grpcServerEndpoint, httpProxyOpts)

    http.HandleFunc("/health", func(w http.ResponseWriter, req *http.Request) { fmt.Fprintf(w, "ok") })

    http.ListenAndServe(httpServerEndpoint, mux)
}
```

Surprisingly in started throwing that error after upgrading, one important thing to notice is that it is not breaking anything but it is annoying and makes logs hard to read.

**Comment by johanbrandhorst** [comment]
Ah I think I see what's happening. In 2.21 we changed some INFO logs to ERROR level logs: https://github.com/grpc-ecosystem/grpc-gateway/pull/4327. You can remove these logs by overwriting the output of the grpc logger:
```
grpclog.SetLoggerV2(grpclog.NewLoggerV2(io.Discard, io.Discard, io.Discard))
```

The error was probably always happening, but you're only noticing because we changed the log level. As to why it's happening, do you update your generator at the same time as you update the runtime library?

**Comment by andreslunchbox** [comment]
Thanks! I'll give that a try.
With generator do you mean these dependencies:
```
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2
google.golang.org/protobuf/cmd/protoc-gen-go
google.golang.org/grpc/cmd/protoc-gen-go-grpc
```
?

**Comment by johanbrandhorst** [comment]
Specifically, `github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway`, yes. But you need to install it to change the generated output. It will depend on how you manage your generation. There are example generation setups in the README.

**Comment by andreslunchbox** [comment]
Okay yeah looks like we updated the generator pretty recently, we are currently using v1.5.1 would that be an issue?
For generation we use the Buf CLI with the default mapping to HTTP semantics in our .proto files.

**Comment by johanbrandhorst** [comment]
v1.5.1 of which generator? Probably not `protoc-gen-grpc-gateway`, right? That would be very old.

**Comment by andreslunchbox** [comment]
Yeah sorry my bad, we actually moved to Buf Remote Plugins and updated the versions off all the generators, this is or `buf.gen.yaml`:

```
version: v2
plugins:
  - remote: buf.build/protocolbuffers/go:v1.34.2
    out: ./gen/go
    opt: paths=source_relative

  - remote: buf.build/grpc/go:v1.5.1
    out: ./gen/go
    opt: paths=source_relative

  - remote: buf.build/grpc-ecosystem/gateway:v2.21.0
    out: ./gen/go
    opt: paths=source_relative

  - remote: buf.build/protocolbuffers/csharp:v27.3
    out: ./gen/csharp
    
  - remote: buf.build/bufbuild/es:v2.0.0
    out: ./gen/ts
    opt:
      - target=ts
      - json_types=true
      - import_extension=ts
```

I can confirm that the generator version v2.21.0 matches the runtime version and we are still seeing:

`ERROR: Failed to extract ServerMetadata from context`
