### ISSUE TITLE
Enum Path Parameter to Swagger

### ISSUE THREAD

**Issue by garyluu** [grpc-ecosystem/grpc-gateway#486]
Seems to be an issue converting a proto file with a path parameter to swagger.  The below is the proto file:

```protobuf
syntax = "proto3";

package thing;

import "google/api/annotations.proto";

message Request {
  EnumThing view = 5;
}

message Response {
  string tasks = 1;
}

enum EnumThing {
  MINIMAL = 0;
  BASIC = 1;
  FULL = 2;
}

service ThingService {
  rpc ListThings(Request) returns (Response) {
    option (google.api.http) = {
      get: "/v1/thing/{view}"
    };
  }
}
```
After converting to yaml, expected:
```yml
      - name: view
        in: path
        required: true
        type: string
        enum: ['MINIMAL', 'BASIC', 'FULL']
```
but received the below instead:
```yml
      - name: view
        in: path
        required: true
        type: thingEnumThing
```
Additionally, `thingEnumThing` isn't defined anywhere.
